#pragma once
#include <memory>
#include <vector>
#include <exception>
#include <map>
#include <string>
#include <sstream>
#include <array>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <iterator>
#include <set>
#include <tuple>
#include <thread>
#include <atomic>
#include <functional>
#include <tuple>
#include <list>
#include <type_traits>
#include <assert.h>
#include <fstream>
#include <mutex>
#include <iostream>
#include <future>
#include <stack>